version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "nestjsrealworld"
      MYSQL_USER: "ebAlm"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
